'use strict';

const API_PORT = `3000`;
const API_TIMEOUT = 10000;
const DEFAULT_API_URL = `http://localhost:${API_PORT}/api`;
const DEFAULT_ARTICLES_LIMIT = 8;
const DEFAULT_PAGE = 1;
const API_BASE_URL = process.env.BASE_URL || DEFAULT_API_URL;

module.exports = {API_PORT, API_TIMEOUT, DEFAULT_API_URL, API_BASE_URL, DEFAULT_ARTICLES_LIMIT, DEFAULT_PAGE};
